{
 "title": "Command Center",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "url_name",
    "label": "URL",
    "query": "SHOW TAG VALUES FROM http_response WITH KEY=server"
   },
   {
    "name": "Host",
    "label": "Docker Host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "Docker_Stack",
    "label": "Docker Stack",
    "query": "SHOW TAG VALUES WITH KEY = \"docker.group\"  "
   }
  ]
 },
 "panels": [
  {
   "title": "Current Download Speed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "speedtest_bits_per_second{direction=\"downstream\"}",
     "legendFormat": "Download Speed"
    }
   ]
  },
  {
   "title": "Halifax",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "San Diego",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Kual Lumpur",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Sydney",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Upload Speed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "format": "decbits",
   "valueName": "current",
   "targets": [
    {
     "expr": "speedtest_bits_per_second{direction=\"upstream\"}",
     "legendFormat": "Upload Speed"
    }
   ]
  },
  {
   "title": "Muinch",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "London",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Atlanta",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime - Enterprise",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "enterprise.ns.obihann.com" }
     ]
    }
   ]
  },
  {
   "title": "Uptime - pfSense",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pfsense.ns.obihann.com" }
     ]
    }
   ]
  },
  {
   "title": "Uptime - PVE",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system",
     "select": [
      [
       { "params": [ "uptime" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve.ns.obihann.com" }
     ]
    }
   ]
  },
  {
   "title": "Down Sites",
   "type": "table",
   "gridPos": { "h": 4, "w": 15, "x": 9, "y": 8 },
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "http_response",
     "query": "SELECT last(\"http_response_code\") FROM \"http_response\" WHERE (\"server\" =~ /^$url_name$/) AND  \"http_response_code\" != 200 AND $timeFilter GROUP BY time($__interval), \"server\" fill(none) ORDER BY time DESC LIMIT 1",
     "select": [
      [
       { "params": [ "http_response_code" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=~", "value": "/^$url_name$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU - Enterprise",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "enterprise.ns.obihann.com" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU - pfSense",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pfsense.ns.obihann.com" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "CPU - PVE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 12 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "* -1 + 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve.ns.obihann.com" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Container CPU Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 9, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_cpu",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "Container Mem Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_container_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "container_name" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_container_mem",
     "select": [
      [
       { "params": [ "usage_percent" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "docker.group", "operator": "=~", "value": "/^$Docker_Stack$/" },
      { "condition": "AND", "key": "host", "operator": "=~", "value": "/^$Host$/" }
     ]
    }
   ]
  },
  {
   "title": "RAM - Enterprise",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "enterprise.ns.obihann.com" }
     ]
    }
   ]
  },
  {
   "title": "RAM - pfSense",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pfsense.ns.obihann.com" }
     ]
    }
   ]
  },
  {
   "title": "RAM - PVE",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 16 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "pve.ns.obihann.com" }
     ]
    }
   ]
  }
 ]
}